services:
  - type: web
    name: omnibox
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    disk:
      name: omnibox-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 7023
